### ISSUE TITLE
Edited tasks should be reflected in the list mode

### ISSUE THREAD

**Issue by ammarbinfaisal1** [ammarbinfaisal/tasks#17]
If user edits a task but doesn't save it and returns to list mode then the changes made there should be shown. There can be unsaved(in some different color) in that task

**Comment by GaurangTandon** [comment]
Since a normal persons' tasks are generally quite small, I doubt there even needs to be any manual save functionality in the first place. It should auto save on every keystroke.

Otherwise, if saving is a necessity, tracking unsaved tasks might add more complexity to the program, and seems unnecessary. Instead, just warn the user when they are existing the edit mode that they will lose unsaved changes on exit.

**Comment by ammarbinfaisal1** [comment]
yeah you are right! all this is absolutely useless.
